### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by caldarolamartin** [hemanthpruthvi/PyAstroPol#1]
I have finished the review for this paper. I believe the paper is ready for acceptance according to the review criteria once minor issues presented below are solved.

**Documentation**
The installation worked easily with python 3.6 and manually installing the listed dependencies. However, I would encourage the author to provide an environment file to prevent possible issues with different versions of the dependencies. Note: I also tried python 3.7 and the plots did not work.
Regarding community guidelines, a description on how to contribute and report issues is missing.

**Software paper**
The salient features of the package are explained, I would suggest some sort of comparison with other software that can be used to get the same results. This will evidence the strength of this software: a simple, fast and reliable way to calculate the Muller matrix without complications.

**Comment by hemanthpruthvi** [comment]
@caldarolamartin  Thank you very much for the valuable review, especially the issue when using the package with Python 3.7.

#### Documentation
 - I have added description as to how to contribute, in the Readme file. 
 - Looks like there is bug with using Tk back-end in certain combination of matplotlib, python and OS ([still an open issue looks like](https://github.com/matplotlib/matplotlib/issues/12074)). I was able to reproduce the problem. As a fix, I have modified codes to not exclusively use Tk. For the interactive plots, users have to choose a compatible back-end on their own.
- Regarding environment file : thank you very much for the suggestion. I have no experience in such setups/assessing  pros and cons. I will look into it.

#### Software paper
I have done the comparison with Zemax OpticStudio&reg; (commercial and expensive) and with my own previous works. I have provided design files and comparison process for the example in __11_KTTCoelostat.ipynb__. However, unless the users have the software license, they would not be able to check for themselves.

**Comment by caldarolamartin** [comment]
@hemanthpruthvi I see you addressed all the issues and added the comparisons with other software, from my side the paper is ready to be published!
